### ISSUE TITLE
Private the repository

### ISSUE THREAD

**Issue by Aldin-SXR** [armanculah/DS_2024_ArmanCulah#1]
Dear @armanculah ,

The lab and homework repositories are supposed to be **private**.

Can you please private this one?

Best regards.
Aldin Kovačević

**Comment by armanculah** [comment]
Dear Professor,

sorry for the mistake; I see the reasons why it should be private but since rarely anyone has my GitHub I thought It wouldn't be a big problem. I made it public so my colleague Anja could check it before turning it in since I failed OOP and wanted someone to run it on their machine as well, so I don't have to fix the executions before the defence.
I will switch it now to private and sorry once more.

Warm regards and best wishes 🧿,
Arman
